spring:
  security:
    user:
      name: user
      password: sa
# In production environment the config server uses a keystore or vault to protect password.
#    password: '{cipher}AQCBEJQaBHFtllY7nnOyW14gwaJbwqzV9CAf9YFPQf310wRonMc45J4cWb3hoJIfcTaMTLa+DDOqCFSDdFiI8PoDUoj44sUV4GLBnlBxtaJp0OF2Sv7H3XLFdOovJksRPYoJW8m5e9GTzwTyQt3IRJ+NuUJRorOQ7Cb8gtKhgSUHMR710lcdGSIanj512Ewi7xcUYUzHLfU0L+wdLX3k3dkJgtMxaJZMSGfREXz6V3ndeCk8mAnFy0tt/G6ftxfzLKQgdd3S7MkfoZBXHL1DdxS+vW+/S0pDrqs8o9WNX9O1VaYokhwymVFRGkJv5ASmerLzmh3YWkzbfqkg6lwxL/npauGcc+EOs9v/bN5e6QcPePfZMMlVVNjBXbP3VoAKLic='

---
spring:
  config:
    activate:
      on-profile: "!ASYNCHRONOUS"

owms:
  partners:
    sps01: tcpip-palettconv
    sps02: tcpip-palett1
    sps03: tcpip-palett2
    sps04: tcpip-cartonconv
    sps05: tcpip-carton1
    sps06: tcpip-carton2

---
spring:
  config:
    activate:
      on-profile: ASYNCHRONOUS

owms:
  partners:
    sps01: osip.res.1
    sps02: osip.res.2
    sps03: osip.res.3
    sps04: osip.res.4
    sps05: osip.res.5

---
spring:
  config:
    activate:
      on-profile: ZILE
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: file:///openwms/data/02-1-load-routing.sql
camunda:
  bpm:
    deployment-resource-pattern: file:///openwms/bpmn/camunda/*.bpmn20.xml,file:///openwms/bpmn/camunda/*.bpmn,file:///openwms/bpmn/camunda/*.dmn11.xml,file:///openwms/bpmn/camunda/*.dmn
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false

---
spring:
  config:
    activate:
      on-profile: ZILEPG
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: /${ZILEPRJ}/data/02-1-load-routing.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/ZILEDB
    username: ZILE
    password: ZILE
camunda:
  bpm:
    deployment-resource-pattern: /${ZILEPRJ}/bpmn/camunda/*.bpmn20.xml,/${ZILEPRJ}/bpmn/camunda/*.bpmn,/${ZILEPRJ}/bpmn/camunda/*.dmn11.xml,/${ZILEPRJ}/bpmn/camunda/*.dmn
